version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker_volumes/rabbitmq/data:/var/lib/rabbitmq
      - ~/.docker_volumes/rabbitmq/log:/var/log/rabbitmq
volumes:
  container-data: